### ISSUE TITLE
Mobile nav slides under the location map

### ISSUE THREAD

**Issue by surreymagpie** [surreymagpie/eleventy-cornerhouse#30]

**Comment by surreymagpie** [comment]
Searching `leaflet.css` for `z-index` properties shows the highest index:

```css
.leaflet-top,
.leaflet-bottom {
	position: absolute;
	z-index: 1000;
	pointer-events: none;
}
```

so our nav and button will need to trump this.
